name: pyspark-cluster

services:
  spark-master:
    container_name: pyspark-master
    build: .
    image: pyspark-image
    entrypoint: ['./entrypoint.sh', 'master']
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
      interval: 5s
      timeout: 3s
      retries: 3
    volumes:
      - ./data:/opt/spark/data
      - ./apps:/opt/spark/apps
      - spark-logs:/opt/spark/spark-events
    env_file:
      - .env.spark
    ports:
      - '9091:8080'
      - '7071:7077'
    restart: unless-stopped

  spark-history-server:
    container_name: pyspark-history
    image: pyspark-image
    entrypoint: ['./entrypoint.sh', 'history']
    depends_on:
      - spark-master
    env_file:
      - .env.spark
    volumes:
      - spark-logs:/opt/spark/spark-events
    ports:
      - '18081:18080'
    restart: unless-stopped

  spark-worker:
    image: pyspark-image
    entrypoint: ['./entrypoint.sh', 'worker']
    depends_on:
      - spark-master
    restart: unless-stopped
    env_file:
      - .env.spark
    volumes:
      - ./data:/opt/spark/data
      - ./apps:/opt/spark/apps
      - spark-logs:/opt/spark/spark-events
  
  minio:
    image: minio/minio
    environment:
      MINIO_REGION_NAME: us-east-1
      MINIO_REGION: us-east-1
      MINIO_DOMAIN: minio
      MINIO_ACCESS_KEY: datalake
      MINIO_SECRET_KEY: datalake
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: datalake
    ports:
      - "9000:9000"
      - "9001:9001"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    entrypoint: >
      /bin/sh -c "
      minio server /data --console-address ':9001' &
      sleep 5;
      mc alias set datalake http://localhost:9000 admin datalake;
      mc mb datalake/datalake;
      tail -f /dev/null"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
      TZ: ${TZ:-Europe/Dublin}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data
      - ./stage:/stage
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: ${PGADMIN_LISTEN_PORT:-5050}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      TZ: ${TZ:-Europe/Dublin}
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - ${PGADMIN_LISTEN_PORT:-5050}:5050
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./stage:/stage
    restart: unless-stopped

volumes:
  spark-logs:
  postgresql_data:
  pgadmin_data: